snippet "a(rchInstall)?" "Install pacman packages" br
RUN pacman --sync --refresh --noconfirm --noprogressbar --quiet && pacman --sync --refresh --sysupgrade --noconfirm --noprogressbar --quiet && pacman --sync --noconfirm --noprogressbar --quiet $1
endsnippet
