#!/bin/bash
#--enable aligncheck \
#--enable gofmt \
#--enable golint \
#--enable gosimple \
#--enable ineffassign \
#--enable interfacer \
#--enable misspell \
#--enable staticcheck \
#--enable structcheck \
#--enable unconvert \
#--enable unparam \
#--enable unused \
#--enable varcheck \
#--enable vet \
#--enable vetshadow \
gometalinter --vendored-linters \
    --exclude '^vendor' \
    --disable-all \
    --enable deadcode \
    --enable dupl --dupl-threshold=100 \
    --enable errcheck --exclude 'error return value not checked \(defer.*Close.*errcheck' \
    --enable goconst \
    --enable gocyclo \
    --enable lll --line-length=160 \
    --deadline 1 \
    $@
