#!/bin/bash
EXTRAS_PATH='/home/dude/android/android-sdk-linux/extras'
EXTRAS_ALL_JARS="$(find "${EXTRAS_PATH}" | grep '.jar$')"
EXTRAS_CLASS_PATH="$(echo ${EXTRAS_ALL_JARS} | tr ' ' ':')"
GRADLE_CACHE_PATH='/home/dude/.gradle/caches/'
GRADLE_CACHE_ALL_JARS="$(find "${GRADLE_CACHE_PATH}" | grep '.jar$')"
GRADLE_CACHE_CLASS_PATH="$(echo ${GRADLE_CACHE_ALL_JARS} | tr ' ' ':')"
GENERATED_CLASS_PATH="$(echo app/build/generated/source/*/debug | tr ' ' ':')"
BUILD_JARS="$(find app/build/intermediates | grep '.jar$')"
BUILD_JARS_CLASSPATH="$(echo ${BUILD_JARS} | tr ' ' ':')"
/usr/bin/javac -cp "${GENERATED_CLASS_PATH}:${EXTRAS_CLASS_PATH}:${GRADLE_CACHE_CLASS_PATH}:${BUILD_JARS_CLASSPATH}:/home/dude/android/android-sdk-linux/platforms/android-23/android.jar:app/src/androidTest/java:app/src/debug/java:app/src/main/java" $@
